### ISSUE TITLE
TOC file does not contain proper version string

### ISSUE THREAD

**Issue by Oxenoth** [MChambers1992/CopyPasta2#3] opened 2020-11-30 13:19 UTC
The "Version" tag inside .toc file is set to `@project-version@`, instead of current TukUI release `1.0.4`.
This breaks some addon managers like WowUp.io - it is using this tag to check for available updates.

**Comment by MChambers1992** [comment] 2020-12-01 10:27
Thanks for letting me know, this should be fixed in the latest commit (https://github.com/MChambers1992/CopyPasta2/commit/1735561486fad9ea2aa0d34882c81b3ce93c0318) and release version.

I'll close this issue as resolved if the issue isn't please feel free to raise another one and I'll take another look.

**Closed as completed** 2020-12-01 13:11 UTC
