### ISSUE TITLE
WoWUp Support

### ISSUE THREAD

**Issue by KevinTyrrell** [MChambers1992/CopyPasta2#9] opened 2023-06-27 11:17 UTC
![image](https://github.com/MChambers1992/CopyPasta2/assets/12791400/86e02f94-3aab-4b69-9334-a9e59acf22ef)

Upon importing the addon with the Github link `https://github.com/MChambers1992/CopyPasta2` the above error is generated.

I believe a release is needed that specifies `-wrath` at the end of the zip file name. For example `CopyPasta2-wrath.zip`

**Comment by wduda** [comment] 2023-06-30 06:54
The `-wrath`  would only be for a Classic version of the plugin. The issue is more that there are no releases being generated on GitHub just yet. This could be automated with GitHub actions so I hope @MChambers1992 can add that :-)

**Comment by rickvdwetering** [comment] 2023-08-15 18:02
> The `-wrath` would only be for a Classic version of the plugin. The issue is more that there are no releases being generated on GitHub just yet. This could be automated with GitHub actions so I hope @MChambers1992 can add that :-)

I agree, then we can just update it with WowUp github token support.

**Comment by MChambers1992** [comment] 2023-11-14 14:43
Hey guys, I will look to update this and potentially automate builds with GitHub actions, my concern is that without manually updating I can't verify the updated add-on functions as expected. I'll spend some time looking into it though

**Comment by MChambers1992** [comment] 2023-11-14 14:47
@wduda if you have experience with creating the .yaml files required for the GitHub action to function (I guess using this action: https://github.com/BigWigsMods/packager) then feel free to submit a PR and I'll configure the Action at a later date

**Comment by wduda** [comment] 2023-12-07 22:12
I do, but cannot say anything timeline-wise, just started a new job a few weeks ago. So if anyone else wants to give it a try don't wait for me. I have this issue subscribed, however.

**Comment by MChambers1992** [comment] 2024-02-15 08:35
This is still on my radar @wduda but I just haven't gotten around to it yet. I've been learning a little bit about building Git Actions so I might use this issue as a test for that.

**Comment by wduda** [comment] 2024-02-16 07:30
I also did not have time for personal reasons. But maybe this can help, it is the definition of a github action for a plugin for another game that I wrote. It is not ideal (builds are triggered manually by adding a tag name and creating a draft release oh GitHub) but would give you a starting point:

https://github.com/wduda/TravelWindowII/blob/main/.github/workflows/release.yml

**Comment by MChambers1992** [comment] 2024-08-15 14:32
Closing this issue as a duplicate, this will be resolved when I tackle https://github.com/MChambers1992/CopyPasta2/issues/13. Appreciate the help @wduda.

**Closed as completed by MChambers1992** 2024-08-15 14:32 UTC
